### ISSUE TITLE
Gestión de proyectos de software

### ISSUE THREAD

**Issue by ThorSampy** [SistemasTecTlaxiaco/infografia-ThorSampy-1#3]
![Infografia_Sam](https://user-images.githubusercontent.com/72049122/132163907-c775b1bf-c4af-4e6f-8823-7fe0b792260a.png)

**Comment by CarlosSD16** [comment]
Revisado calificación:18% falto poner referencias de donde se sacó la información , en los demás puntos abarcó lo te,así indicados y asignación de imágenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
